[workspace]
members = [
  "hsm-1h-3s",
  "hsm-2h-2s",
  "hsm0",
  "hsm1",
  "state-result",
  "xtask",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [ "Wink Saville<wink@saville.com>" ]

